//! Async netlink protocol implementation for Linux.
//!
//! This module provides a complete netlink implementation from scratch,
//! supporting RTNetlink (routing), traffic control, and other subsystems.
//!
//! # Quick Start
//!
//! ```ignore
//! use nlink::netlink::{Connection, Route};
//!
//! let conn = Connection::<Route>::new()?;
//!
//! // Query interfaces
//! let links = conn.get_links().await?;
//! for link in &links {
//!     println!("{}: {}", link.ifindex(), link.name_or("?"));
//! }
//!
//! // Build ifindex -> name map for resolving routes/addresses
//! let names = conn.get_interface_names().await?;
//! ```
//!
//! # Event Monitoring
//!
//! Subscribe to multicast groups and use the stream API to monitor events:
//!
//! ```ignore
//! use nlink::netlink::{Connection, Route, RtnetlinkGroup, NetworkEvent};
//! use tokio_stream::StreamExt;
//!
//! let conn = Connection::<Route>::new()?;
//! conn.subscribe(&[RtnetlinkGroup::Link, RtnetlinkGroup::Ipv4Addr])?;
//!
//! let mut events = conn.events().await;
//! while let Some(event) = events.next().await {
//!     match event? {
//!         NetworkEvent::NewLink(link) => println!("New link: {:?}", link.name),
//!         NetworkEvent::NewAddress(addr) => println!("New address: {:?}", addr.address),
//!         _ => {}
//!     }
//! }
//! ```
//!
//! # Traffic Control (TC)
//!
//! The `tc` module provides typed configuration for qdiscs:
//!
//! ```ignore
//! use nlink::netlink::tc::NetemConfig;
//! use std::time::Duration;
//!
//! // Add network emulation with delay and packet loss
//! let netem = NetemConfig::new()
//!     .delay(Duration::from_millis(100))
//!     .jitter(Duration::from_millis(10))
//!     .loss(1.0)  // 1% packet loss
//!     .build();
//!
//! conn.add_qdisc("eth0", netem).await?;
//!
//! // Update the configuration
//! let updated = NetemConfig::new()
//!     .delay(Duration::from_millis(50))
//!     .build();
//! conn.change_qdisc("eth0", "root", updated).await?;
//!
//! // Delete the qdisc
//! conn.del_qdisc("eth0", "root").await?;
//! ```

pub mod action;
pub mod addr;
pub mod attr;
pub mod audit;
pub mod batch;
pub mod bridge_vlan;
mod builder;
pub mod config;
pub mod connection;
pub mod connector;
pub mod diagnostics;
pub mod dispatcher;
pub mod dump_stream;
mod error;
pub mod events;
pub mod fdb;
pub mod fib_lookup;
pub mod filter;
#[cfg(test)]
mod fixtures;
pub mod genl;
pub mod impair;
mod interface_ref;
pub mod link;
pub mod mdb;
pub mod message;
pub mod messages;
pub mod mpls;
pub mod namespace;
pub mod namespace_events;
#[cfg(feature = "namespace_watcher")]
pub mod namespace_watcher;
pub mod neigh;
pub mod netfilter;
pub mod nexthop;
pub mod nftables;
pub mod parse;
pub mod parse_params;
/// Property-based parser-robustness harnesses (Plan 193 phase 2-3).
#[cfg(test)]
mod parser_proptest;
pub mod pool;
mod protocol;
pub mod psched;
pub mod ratelimit;
pub mod reflector;
pub mod resync;
pub mod resync_ext;
pub mod route;
pub mod route_resync;
pub mod rule;
pub mod selinux;
#[cfg(feature = "sockdiag")]
mod sockdiag;
mod socket;
pub mod srv6;
pub mod stats;
mod stream;
pub mod sys_sizeof;
pub mod sysctl;
pub mod tc;
pub mod tc_handle;
pub mod tc_options;
pub mod tc_recipe;
pub(crate) mod tc_recipe_internals;
/// Byte-level assertions on encoder output, shared by the `tc` and
/// `action` test modules.
#[cfg(test)]
pub(crate) mod test_support;
pub mod types;
pub mod uevent;
pub mod xfrm;

pub use attr::{AttrIter, NlAttr};
pub use batch::{Batch, BatchResults};
pub use builder::{MessageBuilder, NestToken};
pub use connection::{Connection, RtnetlinkGroup};
pub use dispatcher::{Dispatcher, DispatcherEvent};
pub use error::{ChainWalk, Error, Result};
pub use events::NetworkEvent;
// DPLL family marker is generated by `#[genl_family]` inside the
// dpll module (not in protocol.rs like the other GENL markers).
// Surface it at `nlink::netlink::Dpll` for path-symmetry with
// `Wireguard`, `Macsec`, `Devlink`, etc.
pub use genl::dpll::Dpll;
pub use interface_ref::InterfaceRef;
pub use message::{MessageIter, NLMSG_HDRLEN, NlMsgHdr, NlMsgType};
pub use namespace::NamespaceSpec;
pub use namespace_events::{NamespaceEventSubscriber, NamespaceNetlinkEvent};
#[cfg(feature = "namespace_watcher")]
pub use namespace_watcher::{
    NamespaceEvent, NamespaceEventStream, NamespaceWatcher, NamespaceWatcherConfig,
};
pub use parse::{FromNetlink, ToNetlink};
// Macro-only re-export of the sealed-trait module; downstream
// code should NOT name these paths directly. See
// `protocol::__macro_seal` for the contract — only the
// `#[genl_family]` attribute macro is authorized to emit
// `impl __macro_seal::*`.
#[doc(hidden)]
pub use protocol::__macro_seal;
pub use protocol::{
    AsyncProtocolInit, Audit, Connector, Devlink, Ethtool, FibLookup, Generic, KobjectUevent,
    Macsec, Mptcp, Netfilter, Nftables, Nl80211, ProtocolState, Route, SELinux, SockDiag,
    Wireguard, Xfrm, construction,
};
// Internal-use re-export so callers outside `netlink/` (e.g.
// `crate::macros::genl_dispatch`) can reach the batch-size const
// without naming the private `socket` module directly.
#[cfg(feature = "syscall_batch")]
pub(crate) use socket::NL_BATCH_SIZE;
pub use socket::{NetlinkSocket, Protocol, rtnetlink_groups};
pub use stream::{EventSource, EventSubscription, OwnedEventStream};
pub use tc_options::NetemParameter;
